### ISSUE TITLE
Create unit controller

### ISSUE THREAD

**Issue by aldopain** [aldopain/corpwars#8]
Добавить:

- [x] Возможность выбора юнита по дабл клику на него

- [ ] Возможность выделить несколько юнитов?????

- [x] Возможность отдавать приказы на перемещение

**Comment by fshpsmgc** [comment]
1) Не уверен, зачем делать выбор по двойному клику, когда есть вполне себе удобная левая кнопка мыши.
2) Не уверен, зачем выбирать несколько юнитов в экономической-то стратегии.
