### ISSUE TITLE
Override ToString function to NavigationRoute

### ISSUE THREAD

**Issue by fshpsmgc** [aldopain/corpwars#86]
Интерфейсу юнитов нужно знать, начальную и конечную точку, поэтому я хочу, чтобы ToString отдавал что-то вроде <начало пути> - <конец пути>

**Comment by aldopain** [comment]
Сделаю завтра утром. 
NavigationRoute, напомню, имеет N количество точек маршрута, которые можно конфигурять как угодно. 
Тебе отдавать в стринге все точки или только первую и последнюю?
Если первая и последняя одинаковые?

**Comment by fshpsmgc** [comment]
Короче, смотри что я хочу
В окне со списком юнитов я хочу в самом левом списке выводить икноку, название (?) и их краткий маршрут, а при нажатии на кнопку в окне информации выводить уже все точки, по которым он ходит
Этот краткий маршрут в моей голове был в стиле <начало> - <конец>, но у этого подхода есть несколько проблем
Короче, пока сделай в таком виде, а если он ходит по кругу, то выводи что-то вроде Loop (Town Name)
